# Generated by Django 4.2.1 on 2023-07-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Sci_Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Horror', 'Humor'), ('Novel', 'Novel'), ('Bengali_Classic_Novel', 'Bengali Classic Novel'), ('Sucpence', 'Sucpence'), ('Short_Story', 'Short Story'), ('Romance', 'Romance'), ('Modern', 'Modern'), ('Retro', 'Retro'), ('History', 'History'), ('Religious', 'Religious'), ('Documentary', 'Documentary'), ('Self_Help', 'Self Help'), ('High_Life_Spirituality', 'High Life Spirituality'), ('How_To', 'How To'), ('Bengali_Novel', 'Bengali Novel')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('pulication_date', models.DateField(auto_now_add=True)),
                ('last_publication', models.DateField(auto_now=True, null=True)),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_genre', to='books.bookgenre')),
            ],
        ),
    ]
