# Generated by Django 4.2.1 on 2023-06-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookStoreAddBookModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Horror', 'Humor'), ('Novel', 'Novel'), ('Sucpence', 'Sucpence'), ('Short Story', 'Short Story'), ('Romance', 'Romance'), ('Modern', 'Modern'), ('Retro', 'Retro'), ('History', 'History'), ('Religious', 'Religious'), ('Documentary', 'Documentary')], max_length=50)),
                ('first_pub', models.DateField(auto_now_add=True)),
                ('last_pub', models.DateField()),
            ],
        ),
    ]
