# Generated by Django 4.2.1 on 2023-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookstoreaddbooksmodel_delete_bookstoreaddbookmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoreaddbooksmodel',
            name='category',
            field=models.CharField(choices=[('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Horror', 'Humor'), ('Novel', 'Novel'), ('Sucpence', 'Sucpence'), ('Short Story', 'Short Story'), ('Romance', 'Romance'), ('Modern', 'Modern'), ('Retro', 'Retro'), ('History', 'History'), ('Religious', 'Religious'), ('Documentary', 'Documentary'), ('Self Help', 'Self Help')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bookstoreaddbooksmodel',
            name='first_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
