# Generated by Django 4.2.1 on 2023-06-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookstoreaddbooksmodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoreaddbooksmodel',
            name='first_pub',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bookstoreaddbooksmodel',
            name='last_pub',
            field=models.DateField(null=True),
        ),
    ]
