# Generated by Django 4.2.2 on 2023-07-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0002_bookgenre_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='book',
            name='total_copy',
            field=models.IntegerField(default=0),
        ),
    ]
