# Generated by Django 4.2.2 on 2023-07-17 07:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0003_remove_user_birth_date_remove_user_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('provisional_return_date', models.DateTimeField(default=datetime.datetime(2023, 8, 1, 7, 17, 6, 881175, tzinfo=datetime.timezone.utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='lib_users.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('borrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lib_users.borrowbook')),
            ],
        ),
    ]
