# Generated by Django 4.2.2 on 2023-07-17 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0004_borrowbook_returnbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 7, 18, 41, 257264, tzinfo=datetime.timezone.utc)),
        ),
    ]
