# Generated by Django 4.2.2 on 2023-07-17 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0005_alter_borrowbook_provisional_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrowed_books',
            field=models.ManyToManyField(through='lib_users.BorrowBook', to='lib_users.book'),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 7, 35, 13, 244931, tzinfo=datetime.timezone.utc)),
        ),
    ]
