# Generated by Django 4.2.2 on 2023-07-17 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0006_user_borrowed_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 10, 16, 14, 21741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='borrowed_books',
            field=models.ManyToManyField(related_name='user_borrowed_books', through='lib_users.BorrowBook', to='lib_users.book'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='User Wishlist', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ManyToManyField(blank=True, related_name='wishlists', to='lib_users.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='books', to='lib_users.wishlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlists', to='lib_users.wishlist'),
        ),
    ]
