# Generated by Django 4.2.2 on 2023-07-18 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0010_alter_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 10, 36, 44, 276262, tzinfo=datetime.timezone.utc)),
        ),
    ]
