# Generated by Django 4.2.2 on 2023-07-18 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0011_alter_borrowbook_provisional_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='fine',
        ),
        migrations.AddField(
            model_name='returnbook',
            name='is_fine_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 11, 48, 49, 258637, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='borrow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_book', to='lib_users.borrowbook'),
        ),
    ]
