# Generated by Django 4.2.2 on 2023-07-18 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0012_remove_returnbook_fine_returnbook_is_fine_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 2, 17, 21, 25, 264915, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='return_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
