# Generated by Django 4.2.1 on 2023-07-19 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0015_alter_borrowbook_provisional_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 3, 15, 7, 856875, tzinfo=datetime.timezone.utc)),
        ),
    ]
