# Generated by Django 4.2.1 on 2023-07-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0018_alter_borrowbook_provisional_return_date_and_more'),
    ]

    operations = [
    ]
