# Generated by Django 4.2.1 on 2023-07-19 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_users', '0021_alter_borrowbook_provisional_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(choices=[('mystery', 'Mystery'), ('thriller', 'Thriller'), ('sci_fi', 'Sci-Fi'), ('humor', 'Humor'), ('horror', 'Humor'), ('novel', 'Novel'), ('bengali_classic_novel', 'Bengali Classic Novel'), ('sucpence', 'Sucpence'), ('short_story', 'Short Story'), ('romance', 'Romance'), ('modern', 'Modern'), ('retro', 'Retro'), ('history', 'History'), ('religious', 'Religious'), ('documentary', 'Documentary'), ('self_help', 'Self Help'), ('high_life_spirituality', 'High Life Spirituality'), ('how_to', 'How To'), ('bengali_novel', 'Bengali Novel')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='provisional_return_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 7, 23, 0, 370393, tzinfo=datetime.timezone.utc)),
        ),
    ]
