# Generated by Django 4.2.1 on 2023-06-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Student Name')),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
