# Generated by Django 4.2.1 on 2023-06-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='address',
            field=models.TextField(max_length=150, verbose_name='Student Address'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Student Email'),
        ),
        migrations.AlterField(
            model_name='examplemodel',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Student Roll'),
        ),
    ]
