# Generated by Django 4.2.1 on 2023-07-03 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccounttype',
            name='maximum_withdrawal_amount',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='initial_deposit_date',
        ),
        migrations.AddField(
            model_name='bankaccounttype',
            name='maximum_withdrawl_amount',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=8),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='initial_deposite_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 13, 15, 35, 610055)),
        ),
        migrations.AlterField(
            model_name='bankaccounttype',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='street_address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_type', to='accounts.bankaccounttype'),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
